id: A4BE24864
title: 'The Truthful Words of a Sage: An Aspiration Prayer from the Exceedingly Secret,
  Enlightened Heart-Essence of the Ḍākinī'
type: translation
pechas:
- I64C1DCCE
- I295432CC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:39:38.971899
  last_modified_at: 2023-01-04 11:39:38.971908
  collections:
  - Do Khyentse Yeshe Dorje Series
  - Works of Tibetan Masters
alignment_to_base:
  I64C1DCCE/E308: 54A0
  I295432CC/C888: 54A0
